version: '2'
services:
  web:
    restart: always
    image: abiosoft/caddy
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - ./tls:/src/tls
    - ./logs:/src/logs:Z
    environment:
    - ACME_AGREE=true
    - CADDYPATH=/etc/tls
networks:
 default:
   external:
     name: private
